### ISSUE TITLE
功能界面功能改造

### ISSUE THREAD

**Issue by hanahmily** [Esjob-Cloud-DevOps/deployment#1]

**Comment by oracle219** [comment]
1.数据库修改project_base表，增加deploy_type字段，区分代码仓库/主机
2.页面增加select控件，选择发布类型
3.代码中增加projectBase的Model、mapper等相关操作

**Comment by oracle219** [comment]
页面对发布类型、作业云小组添加完毕
数据库操作添加完毕
目前还差页面相关js控制
