### ISSUE TITLE
部署功能改造

### ISSUE THREAD

**Issue by hanahmily** [Esjob-Cloud-DevOps/deployment#2]

**Comment by Zhangxinguo** [comment]
1、部署方式分两个方式：一种是通过ip方式，另外一种是通过发布到nexus仓库；
2、新增部署nexus信息表，保存发布到nexus仓库的地址，跟部署表关联；
3、脚本改造，将shell脚本改为java方式调用

**Comment by Zhangxinguo** [comment]
1、熟悉nexus上传文件脚本；
2、盘古编译解析pom文件获取groupId、artifactId、version等参数、部署流程
3、开始编码改造nexus脚本功能

**Comment by Zhangxinguo** [comment]
1、目前整体流程中部署时，无法将编译的tar包下载到本地，经查找，发现编译完没有将tar上传文件服务器，辉哥初步确定是文件系统问题；
2、改造脚本继续进行中，暂时还需要调试；
3、后续是脚本改造的本地测试和界面改造以及数据存取

**Comment by Zhangxinguo** [comment]
1、盘古编译解析properties文件获取groupId、artifactId和version等参数完成
2、明天改造通过nexus部署部分功能，需要在strategy策略类中添加一个字段，区别部署方式
