### ISSUE TITLE
部署后续功能改造

### ISSUE THREAD

**Issue by hanahmily** [Esjob-Cloud-DevOps/deployment#3]

**Comment by guangyun1013** [comment]
技术方案概要：
1.Tab页增加“后续操作”选项，只有“作业云管理员”有权限操作
2.列表按照发布状态、时间倒序排序
3.操作功能包括作业云发布、发布状态更新，作业云发布只发布应用，不发布作业，考虑集成framework页面
4.部署关联表增加deploy_status字段，标记部署状态

**Comment by guangyun1013** [comment]
3.29：
1.熟悉工程、表结构
2.完成“后续操作”菜单展示

**Comment by guangyun1013** [comment]
3.30:
1.完成dao、service编写
2.页面部分约完成10%
问题：
盘古前端代码可读性差，页面功能开发容易卡壳

**Comment by guangyun1013** [comment]
3.31:
1.页面开发初步完成
问题：
盘古嵌入framework还未进行
